package hub.ebb.jblcluster.eventservice.model;

public enum ApplyDiscountValidationResult {

    OK,
    VOUCHER_RANGE_NOT_FOUND,
    USER_CATEGORY_MISSMATCH,
    DISCOUNT_AMOUNT_HIGHER,
    VOUCHER_ALREADY_USED,
    VOUCHER_PH_MISMATCH,
    DECRYPT_VOUCHER_ERROR,
    DISCOUNT_DISABLED,
    VOUCHER_PARSING_ERROR,
    NO_PAYMENT_SESSION_FOUND,
    VOUCHER_LIMIT_PER_SESSION_REACHED,
    NESTING_DISCOUNT_DISABLED,
    VOUCHER_MAX_USE_REACHED,
    VOUCHER_DAILY_USE_REACHED,
    VOUCHER_NOT_YET_VALID,
    VOUCHER_EXPIRED
}
